# ĐÂY LÀ FILE CẤU HÌNH XƯƠNG SỐNG CỦA SPRING BOOT.
# - Chứa thông tin kết nối Database MySQL (User, Password, URL)
# - Cấu hình cổng chạy Server (Port 8080)
# - Cấu hình Hibernate (Tự động cập nhật bảng, in log SQL)

spring.application.name=EnglishLearningProject
server.port=8080

# Tắt cache Thymeleaf để HTML/CSS thay đổi ngay lập tức không cần restart
spring.thymeleaf.cache=false

spring.config.import=optional:classpath:application-secret.properties

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
