# ĐÂY LÀ FILE CẤU HÌNH XƯƠNG SỐNG CỦA SPRING BOOT.
# - Chứa thông tin kết nối Database MySQL (User, Password, URL)
# - Cấu hình cổng chạy Server (Port 8080 or 8081)
# - Cấu hình Hibernate (Tự động cập nhật bảng, in log SQL)

spring.application.name=EnglishLearningProject
server.port=8080


spring.thymeleaf.cache=false

spring.config.import=optional:classpath:application-secret.properties

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# Mail Configuration (SMTP Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App URL for reset link
app.url=http://localhost:${server.port}
