@startuml
left to right direction

actor Guest
actor User
actor Admin

' Kế thừa actor
User --|> Guest
Admin --|> User

rectangle "English Learning System" {

  'Guest
  Guest --> (Browse Lessons)
  Guest --> (Do Dictation)
  Guest --> (Practice Speaking)
  Guest --> (Register / Login)

  'User
  User --> (View Dictation Result)
  User --> (View Speaking Result)
  User --> (Save Progress)
  User --> (Comment)
  User --> (Logout)

  'Admin
  Admin --> (Manage Content)
  Admin --> (Manage Users)
  Admin --> (Manage Comments)

  'Quan hệ
  (Do Dictation) ..> (View Dictation Result) : <<include>>
  (Practice Speaking) ..> (View Speaking Result) : <<include>>
}
@enduml